### ISSUE TITLE
JDBC Connection Reset Errors

### ISSUE THREAD

**Issue by grovescc** [neurotech/node-edumate#1]
Hello, Experimenting with you solution at the moment - thanks for sharing!

Just checking if you've come across this particular issue before and have any clues when running a query?

Error: Error running static method
com.ibm.db2.jcc.am.yn: [jcc][t4][2030][11211][3.57.82] A communication error occurred during operations on the connection's underlying socket, socket input stream, or socket output stream.  Error location: Reply.fill().  Message: Connection reset. ERRORCODE=-4499, SQLSTATE=08001

**Comment by neurotech** [comment]
Hi @grovescc - seems like a connection issue related to your Edumate install, possibly.

This is the error page from IBM for those codes: https://www-304.ibm.com/support/docview.wss?uid=swg21403644

It could also be the machine you're running the node application on, or possibly your organisation's network firewall setup.

If you can share a bit more info about what you're doing I might be able to help further.

**Comment by grovescc** [comment]
I'm trying to run queries on a hosted instance of Edumate and do all sorts of great things with the data. I've only been able to extract some messy student data from their XML-RPC API: http://helpdesk.edumate.com.au/entries/62486504-Expanding-the-XML-RPC-API

I'm guessing this solution was designed for on-premises installs? 

Hobsons are recommending using this product to interface with their hosted solution (we're hosted): DataDirect SequeLink Client for ODBC for DB2 6.0

Thought it may have been that the driver needed to use SSL using some options from here - appear to be getting "handshake_failure" errors: https://www-01.ibm.com/support/knowledgecenter/SSEPGG_9.1.0/com.ibm.db2.udb.apdv.java.doc/doc/rjvdsprp.htm

**Comment by neurotech** [comment]
Correct - this has been developed and tested with our on-site install of Edumate here at Rosebank. I have no experience with Hobsons' cloud-hosted solution, unfortunately!

**Comment by grovescc** [comment]
Appreciate your help. It looks like for the hosted version you need to work with Hobsons more closely and purchase a SequeLink driver: https://www.progress.com/sequelink

**Comment by neurotech** [comment]
Ugh, that's a shame. Sorry to hear that you're hitting roadblocks. I will close the issue for now.

**Comment by grovescc** [comment]
I've been able to connect to the hosted database. I've written a utility in ruby here to interact with it: https://github.com/ccmschools/EduMine

Your solution gave me the clue to contact Hobsons about database access. Thank you for sharing your code and for your help on this.

**Comment by neurotech** [comment]
My pleasure - good work!
